"""The NLP layer's parsing, serialisation, and refusal discipline (issue #65).

`explain.py` shipped with no tests, which is how it kept two unhandled tracebacks — a
reply that is not JSON, and a `mode` value `reasoning.Mode` does not have — and how the
refusal path came to be generated by a language model rather than stated by the code.

Nothing here touches the network. The client is a parameter with a lazy default, so a stub
returning canned completions exercises everything except the API call itself; the one test
that would need a key asserts the opposite — that no call happens.
"""

from __future__ import annotations

import unittest

from decision_graph import explain
from decision_graph.reasoning import Answer, Mode, Path, Step


class StubClient:
    """Records the prompts it is given and replays canned replies."""

    def __init__(self, *replies: str) -> None:
        self._replies = list(replies)
        self.prompts: list[str] = []
        self.chat = self  # so `client.chat.completions.create(...)` resolves here
        self.completions = self

    def create(self, **kwargs):
        self.prompts.append(kwargs["messages"][0]["content"])
        reply = self._replies.pop(0)

        class _Message:
            content = reply

        class _Choice:
            message = _Message()

        class _Response:
            choices = [_Choice()]

        return _Response()


def _answer(*, found: bool, tier: str = "explicit", fallback: bool = False) -> Answer:
    if not found:
        return Answer(
            mode=Mode.WHY,
            start_node_id=1,
            paths=[],
            used_inferred_fallback=False,
            explanation="no path",
        )
    step = Step(
        edge_id=10,
        edge_type="motivated_by",
        tag="inferred" if tier == "inferred" else "explicit",
        evidence_tier=tier,
        from_node_id=1,
        to_node_id=2,
        extractor="synthesis_closes_cluster",
        source_ref=None,
    )
    path = Path(
        node_ids=[1, 2],
        steps=[step],
        titles={1: "decision", 2: "the motivating issue"},
        types={1: "decision", 2: "issue"},
    )
    return Answer(
        mode=Mode.WHY,
        start_node_id=1,
        paths=[path],
        used_inferred_fallback=fallback,
        explanation="1 path",
    )


class ParseIntentTest(unittest.TestCase):
    def test_extracts_query_and_mode(self) -> None:
        client = StubClient('{"query": "#5898", "mode": "impact"}')
        self.assertEqual(explain.parse_intent("what breaks if 5898 is reverted?", client),
                         ("#5898", "impact"))

    def test_non_json_reply_is_reported_not_raised_as_a_decode_error(self) -> None:
        # What every model does occasionally, and what used to reach the user as a
        # JSONDecodeError traceback out of the CLI.
        client = StubClient("Sure! Here is the JSON you asked for.")
        with self.assertRaises(explain.ExplainError) as caught:
            explain.parse_intent("why?", client)
        self.assertIn("did not return JSON", str(caught.exception))

    def test_a_mode_the_engine_does_not_have_falls_back_to_why(self) -> None:
        # `Mode("unknown")` is a ValueError raised from inside the CLI. A question that is
        # neither causal nor forward-looking is a normal thing to ask.
        client = StubClient('{"query": "redirect code", "mode": "unknown"}')
        self.assertEqual(explain.parse_intent("tell me about redirects", client)[1], "why")

    def test_an_empty_search_term_is_an_error(self) -> None:
        # Retrieval on "" matches everything, and the first candidate of everything is not
        # an answer to anything.
        client = StubClient('{"query": "   ", "mode": "why"}')
        with self.assertRaises(explain.ExplainError):
            explain.parse_intent("hello", client)

    def test_a_json_array_is_not_an_object(self) -> None:
        client = StubClient('["why"]')
        with self.assertRaises(explain.ExplainError):
            explain.parse_intent("why?", client)


class SummarizeTest(unittest.TestCase):
    def test_a_refusal_is_stated_by_the_code_and_never_generated(self) -> None:
        # The rule the module exists to enforce. 8 of the 18 §9 outcomes are refusals, and
        # a model asked to "politely state that the graph does not contain the answer" is
        # not making the same claim the engine is.
        client = StubClient("this reply must never be used")
        summary = explain.summarize_answer("why?", _answer(found=False), client)
        self.assertEqual(summary, explain.NO_ANSWER)
        self.assertEqual(client.prompts, [], "a refusal was sent to the model")

    def test_a_refusal_needs_no_client_at_all(self) -> None:
        # So an unconfigured or unreachable endpoint cannot turn a correct refusal into a
        # crash. Passing None would raise inside get_client() if this path called it.
        self.assertEqual(
            explain.summarize_answer("why?", _answer(found=False)), explain.NO_ANSWER
        )

    def test_the_prompt_carries_the_evidence_tier(self) -> None:
        client = StubClient("A summary.")
        explain.summarize_answer("why?", _answer(found=True, tier="corroborated"), client)
        prompt = client.prompts[0]
        self.assertIn("evidence tier=corroborated", prompt)
        self.assertIn("[corroborated]", prompt)

    def test_an_inferred_fallback_is_called_out_in_the_prompt(self) -> None:
        client = StubClient("A summary.")
        explain.summarize_answer(
            "why?", _answer(found=True, tier="inferred", fallback=True), client
        )
        self.assertIn("INFERRED", client.prompts[0])

    def test_an_explicit_answer_carries_no_inferred_caveat(self) -> None:
        client = StubClient("A summary.")
        explain.summarize_answer("why?", _answer(found=True), client)
        self.assertNotIn("INFERRED", client.prompts[0])


class RenderPathsTest(unittest.TestCase):
    def test_every_edge_line_names_its_tier(self) -> None:
        rendered = explain.render_paths(_answer(found=True, tier="explicit"))
        self.assertIn("motivated_by [explicit]", rendered)
        self.assertIn("evidence tier=explicit", rendered)

    def test_no_paths_renders_empty_rather_than_inventing_a_placeholder(self) -> None:
        self.assertEqual(explain.render_paths(_answer(found=False)), "")


class AskPrintsItsEvidenceTest(unittest.TestCase):
    """§7: every Why/Impact answer carries the traversal that produced it.

    `dg ask` printed prose alone, which reads the same whether it rests on four
    corroborated edges or one inferred guess. The modules are patched rather than a
    database seeded because the property under test is what `cmd_ask` puts on screen, and
    that should hold on an empty graph and a full one alike.
    """

    def _run(self, answer: Answer, summary: str = "A plain-English summary.") -> str:
        import argparse
        import io
        import os
        from contextlib import redirect_stdout
        from unittest import mock

        from decision_graph import cli, db, explain, reasoning, retrieval

        candidate = mock.Mock(node_id=1, node_type="decision", title="a decision")
        out = io.StringIO()
        with mock.patch.dict(os.environ, {"DATABASE_URL": "postgresql://stub"}), \
             mock.patch.object(db, "connect"), \
             mock.patch.object(retrieval, "find_candidates", return_value=[candidate]), \
             mock.patch.object(reasoning, "reason", return_value=answer), \
             mock.patch.object(explain, "parse_intent", return_value=("x", "why")), \
             mock.patch.object(explain, "summarize_answer", return_value=summary), \
             redirect_stdout(out):
            cli.cmd_ask(argparse.Namespace(question="why?"), [])
        return out.getvalue()

    def test_the_trace_is_printed_with_the_prose(self) -> None:
        printed = self._run(_answer(found=True))
        self.assertIn("motivated_by [explicit]", printed, "no trace was printed")
        self.assertIn("A plain-English summary.", printed)

    def test_an_inferred_answer_says_so_before_the_prose(self) -> None:
        printed = self._run(_answer(found=True, tier="inferred", fallback=True))
        self.assertIn("INFERRED FALLBACK", printed)
        self.assertLess(
            printed.index("INFERRED FALLBACK"),
            printed.index("A plain-English summary."),
            "the warning must reach the reader before the confident paragraph does",
        )

    def test_a_refusal_prints_the_engines_words(self) -> None:
        printed = self._run(_answer(found=False), summary=explain.NO_ANSWER)
        self.assertIn("no answer", printed)


if __name__ == "__main__":
    unittest.main()
